#!/usr/bin/env bash

REPO="https://github.com/BurntSushi/ripgrep"
DEST=~/.local/share
BIN=~/.local/bin
MAN=~/.local/share/man/man1
COMPLETION=~/.zsh/completion

# Get latest release version
LOCATION=$(curl -si $REPO/releases/latest | grep -i 'location:*')
REGEX='releases/tag/([0-9\.]+)'

[[ $LOCATION =~ $REGEX ]]
TAG=${BASH_REMATCH[1]}

RG_VERSION=$(rg --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'
[[ $RG_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "rg is up-to-date: v$TAG"
  exit 0
fi

echo "Installing rg: v$TAG"

FILE_STEM="ripgrep-${TAG}-aarch64-unknown-linux-gnu"
curl --create-dirs --progress-bar -Lo $DEST/$FILE_STEM.tar.gz $REPO/releases/download/$TAG/$FILE_STEM.tar.gz

# Validate the checksum
SHA256=$(cd $DEST && sha256sum $FILE_STEM.tar.gz)
CHECKSUM=$(curl -sL $REPO/releases/download/$TAG/$FILE_STEM.tar.gz.sha256)

if [[ "$SHA256" != "$CHECKSUM" ]]; then
  echo "ripgrep checksums do NOT match"
  rm $DEST/$FILE_STEM.tar.gz
  exit 1
fi

# Remove existing install
rm -r $DEST/ripgrep 2> /dev/null
rm $BIN/rg 2> /dev/null
rm $MAN/rg.1 2> /dev/null
rm $COMPLETION/_rg 2> /dev/null

# Extract the tarball
cd $DEST && tar xvzf $FILE_STEM.tar.gz --transform s/$FILE_STEM/ripgrep/ && rm $FILE_STEM.tar.gz

# Symlink the command
mkdir -p $BIN && cd $BIN && ln -s $DEST/ripgrep/rg rg

# Set up the man page
mkdir -p $MAN && cd $MAN && ln -s $DEST/ripgrep/doc/rg.1 rg.1

# Set up completions
mkdir -p $COMPLETION && cd $COMPLETION && ln -s $DEST/ripgrep/complete/_rg _rg
