#!/usr/bin/env bash

REPO="https://github.com/sharkdp/bat"
DEST=~/.local/share

# Get latest release version
LOCATION=$(curl -si $REPO/releases/latest | grep -i 'location:*')
REGEX='releases/tag/v([0-9\.]+)'

[[ $LOCATION =~ $REGEX ]]
TAG=${BASH_REMATCH[1]}

BAT_VERSION=$(bat --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'
[[ $BAT_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "bat is up-to-date: v$TAG"
  exit 0
fi

echo "Installing bat: v$TAG"

curl --create-dirs --progress-bar -Lo $DEST/bat.deb $REPO/releases/download/v$TAG/bat_${TAG}_arm64.deb
sudo dpkg -i $DEST/bat.deb
rm $DEST/bat.deb
