#!/usr/bin/env bash

REPO="https://github.com/ClementTsang/bottom"

# Get latest release version
LOCATION=$(curl -si $REPO/releases/latest | grep -i 'location:*')
REGEX='releases/tag/([0-9\.]+)'

[[ $LOCATION =~ $REGEX ]]
TAG=${BASH_REMATCH[1]}

BOTTOM_VERSION=$(btm --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'
[[ $BOTTOM_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "bottom is up-to-date: v$TAG"
  exit 0
fi

if [ -z "$CURRENT_TAG" ]; then
  echo "Installing bottom: v$TAG"
else
  echo "Updating bottom: v$TAG"
fi

~/.cargo/bin/cargo install bottom

# Autocompletion
curl --create-dirs -Lo /tmp/bottom/completion.tar.gz $REPO/releases/download/$TAG/completion.tar.gz
cd /tmp/bottom && tar xvzf completion.tar.gz

sudo cp /tmp/bottom/btm.bash /etc/bash_completion.d/btm.bash
sudo cp /tmp/bottom/_btm /usr/share/zsh/site-functions/_btm
cp /tmp/bottom/btm.nu $HOME/.config/nushell/btm.nu

rm -fr /tmp/bottom
