#!/usr/bin/env sh

# Set up repos
# ------------

# wezterm
curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
echo 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list

# Install
# -------

sudo apt update
sudo apt install -y sway waybar swayidle swaylock wezterm
sudo apt install --fix-broken
