#!/usr/bin/env bash

REPO=https://github.com/mfaerevaag/wd
DEST=~/.local/share/wd
MAN=~/.local/share/man/man1
COMPLETION=~/.zsh/completion

# Get latest release version
LOCATION=$(curl -si $REPO/releases/latest | grep -i 'location:*')
REGEX='releases/tag/v([0-9\.]+)'

[[ $LOCATION =~ $REGEX ]]
TAG=${BASH_REMATCH[1]}

WD_VERSION=$($DEST/wd.sh --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'

[[ $WD_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "wd is up-to-date: v$TAG"
  exit 0
fi

if [ -d $DEST ]; then
  echo "Updating wd: v$TAG"

  cd $DEST && git pull
else
  echo "Installing wd: v$TAG"

  git clone --depth 1 $REPO.git $DEST
fi

# Remove existing install
rm -f $MAN/wd.1
rm -f $COMPLETION/_wd.sh

# Set up the man page
mkdir -p $MAN && cd $MAN && ln -s $DEST/wd.1 wd.1

# Set up completions
mkdir -p $COMPLETION && cd $COMPLETION && ln -s $DEST/_wd.sh _wd.sh

# Set up some warp points
$DEST/wd.sh addcd ~/.local/share/chezmoi
mkdir -p ~/working && $DEST/wd.sh addcd ~/working ing
mkdir -p ~/workspace && $DEST/wd.sh addcd ~/workspace space
