#!/usr/bin/env bash

source "$CHEZMOI_WORKING_TREE/lib/github-release.sh"

REPO=https://github.com/junegunn/fzf
DEST=~/.local/share/fzf

# Get latest release at least COOLDOWN_DAYS old
TAG=$(github_release_tag "${REPO#https://github.com/}")
TAG=${TAG#v}

if [ -z "$TAG" ]; then
  echo "fzf: no release at least $COOLDOWN_DAYS days old found, skipping"
  exit 0
fi

FZF_VERSION=$(fzf --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'

[[ $FZF_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "fzf is up-to-date: v$TAG"
  exit 0
fi

if [ -d $DEST ]; then
  echo "Updating fzf: v$TAG"

  cd $DEST && git pull
else
  echo "Installing fzf: v$TAG"

  git clone $REPO.git $DEST
fi

cd $DEST && git checkout tags/$TAG
$DEST/install --xdg --key-bindings --completion --no-update-rc
