#!/usr/bin/env bash

source "$CHEZMOI_WORKING_TREE/lib/github-release.sh"

REPO="https://github.com/tmux/tmux"
WORKING=~/working
DEST=~/.local

# Get latest release at least COOLDOWN_DAYS old
TAG=$(github_release_tag "${REPO#https://github.com/}")

if [ -z "$TAG" ]; then
  echo "tmux: no release at least $COOLDOWN_DAYS days old found, skipping"
  exit 0
fi

TMUX_VERSION=$(tmux -V 2> /dev/null)
VERSION_REGEX='[0-9\.]+[a-z]?'
[[ $TMUX_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "tmux is up-to-date: v$TAG"
  exit 0
fi

if [ -z "$CURRENT_TAG" ]; then
  echo "Installing tmux: v$TAG"
else
  echo "Updating tmux: v$TAG"
fi

# Download
curl --create-dirs --progress-bar -Lo $WORKING/tmux.tar.gz $REPO/releases/download/$TAG/tmux-$TAG.tar.gz

# Extract the tarball
cd $WORKING && tar xzf tmux.tar.gz --transform s/tmux-$TAG/tmux/ && rm tmux.tar.gz

# Build and install
cd $WORKING/tmux && ./configure --prefix=$DEST && make && sudo make install

# Cleanup
cd $WORKING && rm -fr tmux
