#!/usr/bin/env bash

REPO=https://github.com/Alexays/Waybar
BIN=/usr/local/bin
DEST=~/.local/share/waybar

# Get latest release version
LOCATION=$(curl -si $REPO/releases/latest | grep -i 'location:*')
REGEX='releases/tag/([0-9\.]+)'

[[ $LOCATION =~ $REGEX ]]
TAG=${BASH_REMATCH[1]}

WAYBAR_VERSION=$(waybar --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'

[[ $WAYBAR_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "waybar is up-to-date: v$TAG"
  exit 0
fi

if [ -d $DEST ]; then
  echo "Updating waybar: v$TAG"

  cd $DEST && git pull
else
  echo "Installing waybar: v$TAG"

  git clone $REPO.git $DEST
fi

# Remove existing install
rm -f $BIN/waybar

cd $DEST
git checkout tags/$TAG
meson setup build
ninja -C build
./build/waybar
sudo ninja -C build install
