#!/usr/bin/env bash

source "$CHEZMOI_WORKING_TREE/lib/github-release.sh"

REPO="https://github.com/neovim/neovim"
DEST=~/.local/share
BIN=~/.local/bin
MAN_DIR=~/.local/share/man/man1

# Get latest release at least COOLDOWN_DAYS old
TAG=$(github_release_tag "${REPO#https://github.com/}")
TAG=${TAG#v}

if [ -z "$TAG" ]; then
  echo "neovim: no release at least $COOLDOWN_DAYS days old found, skipping"
  exit 0
fi

NEOVIM_VERSION=$(nvim --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'
[[ $NEOVIM_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "neovim is up-to-date: v$TAG"
  exit 0
fi

if [ -z "$CURRENT_TAG" ]; then
  echo "Installing neovim: v$TAG"
else
  echo "Updating neovim: v$TAG"
fi

FILE_STEM="nvim-linux-arm64"
curl --create-dirs --progress-bar -Lo $DEST/$FILE_STEM.tar.gz $REPO/releases/download/v$TAG/$FILE_STEM.tar.gz

# Remove existing install
rm -fr $DEST/neovim

# Extract the tarball
mkdir -p $DEST/neovim && cd $DEST && tar xzf $FILE_STEM.tar.gz -C neovim --strip-components 1 && rm $FILE_STEM.tar.gz

# Symlink the command and man page
mkdir -p $BIN && cd $BIN && ln -sf $DEST/neovim/bin/nvim nvim
mkdir -p $MAN_DIR && ln -sf $DEST/neovim/share/man/man1/nvim.1 $MAN_DIR/nvim.1
