#!/usr/bin/env bash

source "$CHEZMOI_WORKING_TREE/lib/github-release.sh"

REPO="https://github.com/dandavison/delta"
DEST=~/.local/share
COMPLETION=~/.zsh/completion

# Get latest release at least COOLDOWN_DAYS old
TAG=$(github_release_tag "${REPO#https://github.com/}")

if [ -z "$TAG" ]; then
  echo "delta: no release at least $COOLDOWN_DAYS days old found, skipping"
  exit 0
fi

DELTA_VERSION=$(delta --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'
[[ $DELTA_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "delta is up-to-date: v$TAG"
  exit 0
fi

if [ -z "$CURRENT_TAG" ]; then
  echo "Installing delta: v$TAG"
else
  echo "Updating delta: v$TAG"
fi

# Remove existing install
rm -f $COMPLETION/_delta

FILENAME="git-delta_${TAG}_arm64.deb"
curl --create-dirs --progress-bar -Lo $DEST/$FILENAME $REPO/releases/download/$TAG/$FILENAME

sudo dpkg -i $DEST/$FILENAME
rm $DEST/$FILENAME

# Generate completions
delta --generate-completion zsh > $COMPLETION/_delta
