#!/usr/bin/env bash

REPO="https://github.com/ClementTsang/bottom"

# Get latest release version
LOCATION=$(curl -si $REPO/releases/latest | grep -i 'location:*')
REGEX='releases/tag/([0-9\.]+)'

[[ $LOCATION =~ $REGEX ]]
TAG=${BASH_REMATCH[1]}

BOTTOM_VERSION=$(btm --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'
[[ $BOTTOM_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "bottom is up-to-date: v$TAG"
  exit 0
fi

if [ -z "$CURRENT_TAG" ]; then
  echo "Installing bottom: v$TAG"
else
  echo "Updating bottom: v$TAG"
fi

~/.cargo/bin/cargo install bottom
