#!/usr/bin/env bash

source "$CHEZMOI_WORKING_TREE/lib/github-release.sh"

REPO="https://github.com/source-foundry/Hack"
DEST=~/.local/share/fonts

# Get latest release at least COOLDOWN_DAYS old
TAG=$(github_release_tag "${REPO#https://github.com/}")

if [ -z "$TAG" ]; then
  echo "Hack font: no release at least $COOLDOWN_DAYS days old found, skipping"
  exit 0
fi

# Get currently installed version, if any
VERSION_FILE="$DEST/Hack/VERSION"
[ -e $VERSION_FILE ] && CURRENT_TAG=$(< $VERSION_FILE) || CURRENT_TAG=""

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "Hack font already installed: $TAG"
  exit 0
fi

# Install the latest version of the font
if [ -z "$CURRENT_TAG" ]; then
  echo "Installing Hack font: $TAG"
else
  echo "Updating Hack font: $TAG"
fi

# Clean up existing font
rm -fr $DEST/Hack

# Download and extract the font
curl --create-dirs --progress-bar -Lo $DEST/Hack-ttf.tar.xz $REPO/releases/download/$TAG/Hack-${TAG}-ttf.tar.xz
cd $DEST && mkdir Hack && tar -xvJf Hack-ttf.tar.xz -C Hack && rm Hack-ttf.tar.xz

# Update font cache
fc-cache -fv

# Save a version file
echo $TAG > $VERSION_FILE
