#!/usr/bin/env bash

source "$CHEZMOI_WORKING_TREE/lib/github-release.sh"

REPO=https://github.com/ledger/ledger
PYTHON_BIN=~/.local/bin
INSTALL=~/.local
DEST=~/.local/share/ledger
BUILD=$DEST/build

# Get latest release at least COOLDOWN_DAYS old
TAG=$(github_release_tag "${REPO#https://github.com/}")
TAG=${TAG#v}

if [ -z "$TAG" ]; then
  echo "ledger: no release at least $COOLDOWN_DAYS days old found, skipping"
  exit 0
fi

LEDGER_VERSION=$(ledger --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'

[[ $LEDGER_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "ledger is up-to-date: v$TAG"
  exit 0
fi

if [ -d $DEST ]; then
  echo "Updating ledger: v$TAG"

  cd $DEST && git pull
else
  echo "Installing ledger: v$TAG"

  git clone $REPO.git $DEST
fi

# Remove existing install
rm -f $INSTALL/bin/ledger

cd $DEST && git checkout tags/$TAG
# acprep uses python3. It must be resolvable on $PATH
PATH=$PATH:$PYTHON_BIN ./acprep update --prefix=$INSTALL --output=$BUILD --boost-suffix=-mt -j3
cd $BUILD && sudo make install
