#!/usr/bin/env bash

source "$CHEZMOI_WORKING_TREE/lib/github-release.sh"

REPO=https://github.com/Alexays/Waybar
PYTHON_BIN=~/.local/bin
BIN=/usr/local/bin
DEST=~/.local/share/waybar

# Get latest release at least COOLDOWN_DAYS old
TAG=$(github_release_tag "${REPO#https://github.com/}")

if [ -z "$TAG" ]; then
  echo "waybar: no release at least $COOLDOWN_DAYS days old found, skipping"
  exit 0
fi

WAYBAR_VERSION=$(waybar --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'

[[ $WAYBAR_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "waybar is up-to-date: v$TAG"
  exit 0
fi

if [ -d $DEST ]; then
  echo "Updating waybar: v$TAG"

  cd $DEST && git checkout master && git pull
else
  echo "Installing waybar: v$TAG"

  git clone $REPO.git $DEST
fi

# Install meson
$PYTHON_BIN/uv tool install --exclude-newer "$(cooldown_cutoff)" meson --upgrade

cd $DEST
git checkout tags/$TAG
$PYTHON_BIN/meson setup build
sudo ninja -j 2 -C build install
