#!/usr/bin/env bash

REPO="https://github.com/BurntSushi/ripgrep"
DEST=~/.local/share
BIN=~/.local/bin
MAN=~/.local/share/man/man1
COMPLETION=~/.zsh/completion

source "$CHEZMOI_WORKING_TREE/lib/github-release.sh"

# Get latest release at least COOLDOWN_DAYS old
TAG=$(github_release_tag "${REPO#https://github.com/}")

if [ -z "$TAG" ]; then
  echo "rg: no release at least $COOLDOWN_DAYS days old found, skipping"
  exit 0
fi

RG_VERSION=$(rg --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'
[[ $RG_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "rg is up-to-date: v$TAG"
  exit 0
fi

if [ -z "$CURRENT_TAG" ]; then
  echo "Installing rg: v$TAG"
else
  echo "Updating rg: v$TAG"
fi

FILE_STEM="ripgrep-${TAG}-aarch64-unknown-linux-gnu"
curl --create-dirs --progress-bar -Lo $DEST/$FILE_STEM.tar.gz $REPO/releases/download/$TAG/$FILE_STEM.tar.gz

# Validate the checksum
SHA256=$(cd $DEST && sha256sum $FILE_STEM.tar.gz)
CHECKSUM=$(curl -sL $REPO/releases/download/$TAG/$FILE_STEM.tar.gz.sha256)

if [[ "$SHA256" != "$CHECKSUM" ]]; then
  echo "ripgrep checksums do NOT match"
  rm $DEST/$FILE_STEM.tar.gz
  exit 1
fi

# Remove existing install
rm -fr $DEST/ripgrep
rm -f $BIN/rg
rm -f $MAN/rg.1
rm -f $COMPLETION/_rg

# Extract the tarball
cd $DEST && tar xvzf $FILE_STEM.tar.gz --transform s/$FILE_STEM/ripgrep/ && rm $FILE_STEM.tar.gz

# Symlink the command
mkdir -p $BIN && cd $BIN && ln -s $DEST/ripgrep/rg rg

# Set up the man page
mkdir -p $MAN && cd $MAN && ln -s $DEST/ripgrep/doc/rg.1 rg.1

# Set up completions
mkdir -p $COMPLETION && cd $COMPLETION && ln -s $DEST/ripgrep/complete/_rg _rg
