#!/usr/bin/env bash

REPO=https://github.com/ledger/ledger
SHIMS=~/.local/share/pyenv/shims
INSTALL=~/.local
DEST=~/.local/share/ledger
BUILD=$DEST/build

# Get latest release version
LOCATION=$(curl -si $REPO/releases/latest | grep -i 'location:*')
REGEX='releases/tag/v([0-9\.]+)'

[[ $LOCATION =~ $REGEX ]]
TAG=${BASH_REMATCH[1]}

LEDGER_VERSION=$(ledger --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'

[[ $LEDGER_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "ledger is up-to-date: v$TAG"
  exit 0
fi

if [ -d $DEST ]; then
  echo "Updating ledger: v$TAG"

  cd $DEST && git pull
else
  echo "Installing ledger: v$TAG"

  git clone $REPO.git $DEST
fi

# Remove existing install
rm -f $INSTALL/bin/ledger

cd $DEST
PATH=$PATH:$SHIMS ./acprep update --prefix=$INSTALL --output=$BUILD --boost-suffix=-mt -j3
cd $BUILD && sudo make install
