#!/usr/bin/env bash

REPO=https://github.com/pyenv/pyenv
DEST=~/.local/share/pyenv
BIN=~/.local/bin

# Get latest release version
LOCATION=$(curl -si $REPO/releases/latest | grep -i 'location:*')
REGEX='releases/tag/v([0-9\.]+)'

[[ $LOCATION =~ $REGEX ]]
TAG=${BASH_REMATCH[1]}

PYENV_VERSION=$(pyenv --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'

[[ $PYENV_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "pyenv is up-to-date: v$TAG"
  exit 0
fi

if [ -d $DEST ]; then
  echo "Updating pyenv: v$TAG"

  cd $DEST && git pull
else
  echo "Installing pyenv: v$TAG"

  git clone --depth 1 $REPO.git $DEST
fi

cd $DEST && src/configure && make -C src

# Remove existing install
rm -f $BIN/pyenv

# Symlink the command
mkdir -p $BIN && cd $BIN && ln -s $DEST/bin/pyenv pyenv

# Install and use latest python3
PYENV_ROOT="$HOME/.local/share/pyenv" $BIN/pyenv install 3
PYENV_ROOT="$HOME/.local/share/pyenv" $BIN/pyenv global 3
