#!/usr/bin/env bash

REPO=https://github.com/vinnymeller/twm
BIN=~/.cargo/bin
MAN=~/.local/share/man/man1

# Get latest release version
LOCATION=$(curl -si $REPO/releases/latest | grep -i 'location:*')
REGEX='releases/tag/v([0-9\.]+)'

[[ $LOCATION =~ $REGEX ]]
TAG=${BASH_REMATCH[1]}

TWM_VERSION=$(twm --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'

[[ $TWM_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "twm is up-to-date: v$TAG"
  exit 0
fi

if [ -z "$CURRENT_TAG" ]; then
  echo "Installing twm: v$TAG"
else
  echo "Updating twm: v$TAG"
fi

# Remove existing install
rm -f $MAN/twm.1

$BIN/cargo install twm

# Set up the man page
mkdir -p $MAN && $BIN/twm --print-man > $MAN/twm.1
