#!/usr/bin/env bash

cmds=("bat" "fd" "vivid")
for cmd in ${cmds[@]}; do
  REPO="https://github.com/sharkdp/$cmd"
  DEST=~/.local/share

  # Get latest release version
  LOCATION=$(curl -si $REPO/releases/latest | grep -i 'location:*')
  REGEX='releases/tag/v([0-9\.]+)'

  [[ $LOCATION =~ $REGEX ]]
  TAG=${BASH_REMATCH[1]}

  CMD_VERSION=$($cmd --version 2> /dev/null)
  VERSION_REGEX='[0-9\.]+'
  [[ $CMD_VERSION =~ $VERSION_REGEX ]]
  CURRENT_TAG=${BASH_REMATCH[0]}

  if [ "$TAG" = "$CURRENT_TAG" ]; then
    echo "$cmd is up-to-date: v$TAG"
    continue
  fi

  echo "Installing $cmd: v$TAG"

  curl --create-dirs --progress-bar -Lo $DEST/$cmd.deb $REPO/releases/download/v$TAG/${cmd}_${TAG}_arm64.deb
  sudo dpkg -i $DEST/$cmd.deb
  rm $DEST/$cmd.deb
done
