#!/usr/bin/env sh

NU=~/.local/bin/nu
BM=~/.config/nushell/bookmark_for_dir.nu

# Set up some bookmarks
cd ~/.local/share/chezmoi && $NU -c "source $BM; bm -a chezmoi"
cd ~/working && $NU -c "source $BM; bm -a ing"
cd ~/workspace && $NU -c "source $BM; bm -a space"
