#!/usr/bin/env bash

REPO="https://github.com/source-foundry/Hack"
DEST=~/.local/share/fonts

# Get latest release version
LOCATION=$(curl -si $REPO/releases/latest | grep -i 'location:*')
REGEX='releases/tag/(v[0-9\.]+)'

[[ $LOCATION =~ $REGEX ]]
TAG=${BASH_REMATCH[1]}

# Get currently installed version, if any
VERSION_FILE="$DEST/Hack/VERSION"
[ -e $VERSION_FILE ] && CURRENT_TAG=$(< $VERSION_FILE) || CURRENT_TAG=""

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "Hack font already installed: $TAG"
  exit 0
fi

# Install the latest version of the font
echo "Installing Hack font: $TAG"

# Clean up existing font
rm -fr $DEST/Hack

# Download and extract the font
curl --create-dirs --progress-bar -Lo $DEST/Hack-ttf.tar.xz $REPO/releases/download/$TAG/Hack-${TAG}-ttf.tar.xz
cd $DEST && mkdir Hack && tar -xvJf Hack-ttf.tar.xz -C Hack && rm Hack-ttf.tar.xz

# Update font cache
fc-cache -fv

# Save a version file
echo $TAG > $VERSION_FILE
