#!/usr/bin/env bash

source "$CHEZMOI_WORKING_TREE/lib/github-release.sh"

cmds=("bat" "fd" "vivid")
for cmd in ${cmds[@]}; do
  REPO="https://github.com/sharkdp/$cmd"
  DEST=~/.local/share

  # Get latest release at least COOLDOWN_DAYS old
  TAG=$(github_release_tag "${REPO#https://github.com/}")
  TAG=${TAG#v}

  if [ -z "$TAG" ]; then
    echo "$cmd: no release at least $COOLDOWN_DAYS days old found, skipping"
    continue
  fi

  CMD_VERSION=$($cmd --version 2> /dev/null)
  VERSION_REGEX='[0-9\.]+'
  [[ $CMD_VERSION =~ $VERSION_REGEX ]]
  CURRENT_TAG=${BASH_REMATCH[0]}

  if [ "$TAG" = "$CURRENT_TAG" ]; then
    echo "$cmd is up-to-date: v$TAG"
    continue
  fi

  if [ -z "$CURRENT_TAG" ]; then
    echo "Installing $cmd: v$TAG"
  else
    echo "Updating $cmd: v$TAG"
  fi

  curl --create-dirs --progress-bar -Lo $DEST/$cmd.deb $REPO/releases/download/v$TAG/${cmd}_${TAG}_arm64.deb
  sudo dpkg -i $DEST/$cmd.deb
  rm $DEST/$cmd.deb
done
