#!/usr/bin/env bash

source "$CHEZMOI_WORKING_TREE/lib/github-release.sh"

REPO="https://github.com/nushell/nushell"
DEST=~/.local/share
BIN=~/.local/bin

# Get latest release at least COOLDOWN_DAYS old
TAG=$(github_release_tag "${REPO#https://github.com/}")

if [ -z "$TAG" ]; then
  echo "nushell: no release at least $COOLDOWN_DAYS days old found, skipping"
  exit 0
fi

NUSHELL_VERSION=$(nu --version 2> /dev/null)
VERSION_REGEX='[0-9\.]+'
[[ $NUSHELL_VERSION =~ $VERSION_REGEX ]]
CURRENT_TAG=${BASH_REMATCH[0]}

if [ "$TAG" = "$CURRENT_TAG" ]; then
  echo "nushell is up-to-date: v$TAG"
  exit 0
fi

if [ -z "$CURRENT_TAG" ]; then
  echo "Installing nushell: v$TAG"
else
  echo "Updating nushell: v$TAG"
fi

FILE_STEM="nu-${TAG}-aarch64-unknown-linux-gnu"
curl --create-dirs --progress-bar -Lo $DEST/$FILE_STEM.tar.gz $REPO/releases/download/$TAG/$FILE_STEM.tar.gz

# Validate the checksum
SHA256=$(cd $DEST && sha256sum $FILE_STEM.tar.gz)
CHECKSUM=$(curl -sL $REPO/releases/download/$TAG/SHA256SUMS | grep $FILE_STEM.tar.gz)

if [[ "$SHA256" != "$CHECKSUM" ]]; then
  echo "nushell checksums do NOT match"
  rm $DEST/$FILE_STEM.tar.gz
  exit 1
fi

# Remove existing install
rm -fr $DEST/nushell
rm -f $BIN/nu

# Extract the tarball
cd $DEST && tar xvzf $FILE_STEM.tar.gz --transform s/$FILE_STEM/nushell/ && rm $FILE_STEM.tar.gz

# Symlink the command
mkdir -p $BIN && cd $BIN && ln -s $DEST/nushell/nu nu
