#!/usr/bin/env bash

DEST=~/.local/share/fzf

if [ -d $DEST ]; then
  cd $DEST && git fetch
  if [[ $(git rev-parse '@') == $(git rev-parse '@{u}') ]]; then
    echo 'fzf is up-to-date'
    exit 0
  else
    echo 'Updating fzf'
    git merge
  fi
else
  echo "Installing fzf"
  git clone --depth 1 https://github.com/junegunn/fzf.git $DEST
fi

$DEST/install --xdg --key-bindings --completion --no-update-rc
